version: "3.9"

services:

  postgres:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  auth_service:
    image: taskforge:latest
    build: .
    container_name: taskforge_auth
    command: uvicorn app.auth_service.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  job_service:
    image: taskforge:latest
    build: .
    container_name: taskforge_job
    command: uvicorn app.job_service.main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./app:/app/app
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  celery_worker:
    image: taskforge:latest
    build: .
    command: celery -A app.worker.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

volumes:
  postgres_data: